{% set version = "2.9.5987" %}

package:
  name: miktex
  version: {{ version }}

source:
  fn: miktex-portable-{{ version }}.exe
  url: http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable-{{ version }}.exe
  sha1: 28232135D6A1A583A31C91676314719A1577C9C0

build:
  skip: True  # [not win]
  number: 0
  binary_relocation: false

requirements:
  build:
    - 7za
    - m2w64-toolchain # to build the wrapper

test:
  commands:
    - pdflatex.exe --help
    - mpm --help

about:
  home: http://miktex.org/
  license: various, see http://miktex.org/copying
  summary: Implementation of TeX/LaTeX for Windows (repackaged binaries)

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - janschulz
