travis:
  secure:
    BINSTAR_TOKEN: HA+XuPSrTfwbtVjMh2zJ9lZquG4nKMQQESmM5Acf8qhiWLUMU1UINtzdOhiGGiIP/VwBAgND7as94GGXuqrZMypWGKL6dhHPkBq4nwxM+vBEcXAgj+wbajpMmG3fZWoQdFdJ23XXOGQUJSkeRHbP+mYRM7U+5RWgtEv2OwPc7cXNyNK0T9jZHlZTTQh3RkZuAn3HAs/Miuy9pzboH1xTFOQKpqeHegxxQsFaN3KFCCgW+3O1or8M9Ew5G8v60Y1qghOevtnXcbWzn0M+XD73M8P/56+wqsZkd0cGvpb3XhfHJ3X5z7Oh1FLz+b0LER47IGIwrZsE8X/waqQMTgMxe3QAHJTHumVGIfbKZod11ZgxNlFWybYtz/rqcp9GgV9AT1Y1IA9aHbXKKX7LJqPEsIRxOpb8JKNC2k6XSrXsCM524BKFQLWdOfaAUIX/hjowvSB7cng9NpXsltz47kcigfr9mPdkT4D8l/TopSAQP0P/Q38h2KjxOLihR3zNDJxhmkSl7c7qb3RsGuWZ1sMEg8W6d8XicfmXWaiLgiqDlVCLbU1Tr5XNZi2MVWJ5wuMagbF+D37W+Y1DFFGOm8ObiDgKgG3/e2oqoSNhFsXhAO8dk16yEDGMs0th24q2BdtDUsi/boHpjHduLxUTRyCn5lUBgP9ey+eUIgH1TRDizVM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
